# Generated by Django 2.1.7 on 2019-03-06 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'iot_facility',
            },
        ),
        migrations.CreateModel(
            name='FacilityReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pir', models.BooleanField()),
                ('temperature', models.IntegerField()),
                ('light', models.IntegerField()),
                ('ultrasonic', models.IntegerField()),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.Facility')),
            ],
            options={
                'db_table': 'iot_facility_reading',
            },
        ),
    ]
