# Generated by Django 2.1.7 on 2019-03-21 05:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20190314_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityReading2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reading_type', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0.0)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.Facility')),
            ],
            options={
                'db_table': 'iot_facility_reading2',
            },
        ),
    ]
