# Generated by Django 2.1.7 on 2019-03-28 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
    ]
