# Generated by Django 2.1.7 on 2019-04-10 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sensemaking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_wasted', models.DateTimeField(default=django.utils.timezone.now)),
                ('aircon_wasted_hours', models.FloatField(default=0.0)),
                ('light_wasted_hours', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'wastage',
            },
        ),
    ]
