# Generated by Django 2.1.7 on 2019-03-27 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reading_type', models.CharField(max_length=5)),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
    ]
