# Generated by Django 2.1.7 on 2019-03-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0002_auto_20190328_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='updated_at',
        ),
    ]
